### ISSUE TITLE
Remove "html5_validators" gem

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#367] opened 2017-02-04 20:33 UTC
I consider the idea to let this "plugin" set client-side validation globally quite inflexible and against least surprise principle.

app/models/concerns/disable_html5_validation.rb

Under some circumstances the generated output is totally wrong:

`<input ... min="min_amount">`.

**Comment by vohmar** [comment] 2017-02-08 08:20
just to be clear, we validate user input on both client and server side. Client side validation is meant to keep away obviously invalid input. But the client side validations are duplicate of subset of validations on server side. We validate on client side that for example phone number and date format is correct, that user cannot send birthday as ident if country is Estonia etc.

**Comment by artur-beljajev** [comment] 2017-02-08 14:54
OK. The ticket is about changing the implementation of client-side validation, not about removal.

**Comment by artur-beljajev** [comment] 2017-11-20 07:23
The longer this task is postponed, the longer it will take to get rid of it.

**Comment by teadur** [comment] 2017-11-20 07:45
What is the proposed new solution ?

**Closed** 2019-05-07 16:38 UTC
