### ISSUE TITLE
Disable contact validation based on postal address

### ISSUE THREAD

**Issue by virtualfeline** [internetee/registry#732] opened 2018-02-21 12:47 UTC
Specifically contact:cc, but also other address fields, as they are no longer collected, displayed or relevant, they should not be an obstacle in updating the contact. Also any errors regarding same will be misleading as registrar has no context for the error anymore nor any means to correct.

**Comment by vohmar** [comment] 2018-02-21 13:13
duplicate of: https://github.com/internetee/registry/issues/731

**Closed by vohmar** 2018-02-21 13:13 UTC
Labels: duplicate
