### ISSUE TITLE
MID auth does not display code on web interface

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#893] opened 2018-06-22 08:43 UTC
MID auth on web interfaces does not display mid auth code in the portal
https://registrar.internet.ee

no code is displayed after entering the phone number - code is sent on the phone though. Entering correct pin results in login.

The sent sms does not identify the environment
Eesti Internet
Authenticating
Kontrollkood
...

**Comment by maciej-szlosarczyk** [comment] 2018-06-26 09:56
Hey @ratM1n, do we have any messages logged for this error? It would greatly help me debug this thing.

**Comment by maciej-szlosarczyk** [comment] 2018-06-26 13:45
Issue was caused by problem in the view, we technically have a test for this, but since it's based on Rack::Test, it produced a false positive:

https://github.com/internetee/registry/blob/master/spec/features/registrar/sign_in/mobile_id_spec.rb

The issue should be fixed, but I opened #900 to avoid this kind of problems in the future.

**Closed** 2018-06-26 14:55 UTC
Labels: bug
