### ISSUE TITLE
Do not allow prices and zones to be permanently deleted

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#522] opened 2017-05-17 03:42 UTC
1. Zone cannot be deleted
2. Price cannot be deleted
3. Price can be expired (button "Expire now"). Sets "valid_to" to current time
4. A user can filter expired/unexpired prices
5. Only unexpired prices are displayed by default

**Comment by artur-beljajev** [comment] 2017-05-17 03:43
@vohmar I had to extract this ticket from #313, since the latter seems too big.

**Comment by artur-beljajev** [comment] 2017-05-17 04:05
Removing this feature entirely seems too drastic. 

What if I have mistakenly added incorrect zone? Say, "con" instead of "com" (we cannot validate this). Will it remain in archive for ever? That list can quickly become a mess.

How about allowing to completely delete any entity, be it a zone, price etc if it is not used by other entities? 
For example, zone can be deleted if no domain uses it. Price can be removed if no domain has been registered with given price. Some confirmation dialog may help mitigating the risk of accidental removal.

> for price list records the archival option could be solved automatically by hiding any records that have end date in the past.
This might be implemented as "active" and "expired" lists, with no connection to the feature in question.

**Comment by vohmar** [comment] 2017-05-22 11:27
We have 'no delete' policy in our registry. So even though it seems unnecessary to keep incorrect entries in the system the risks to take into account to prevent deleting things that are actually necessary is to great. These are low activity records - new zones are entered extremely rarely and pricelist record once or twice a year. So well stick to the no delete approach until we have no actual reason to drop it.

The goal for archiving is to reduce the noise in the UI and speed up the system by keeping the amount of data in the tables of current data to a minimum. We do not reactivate things in our present practice.

**Comment by artur-beljajev** [comment] 2017-05-23 14:00
Timo:

> We have no delete policy on the registry so there should not be an option to actually delete price list record or zone definition. There must be an option to archive outdated and unused records to help admin interface users.
> for price list records the archival option could be solved automatically by hiding any records that have end date in the past.
> For zones there needs to be a validation/constraint that makes impossible archiving a zone with at least one active domain registration.
> In both cases UI has to offer a filter option to browse through archived objects separately or together with active records (ie. include archived records tick)

**Comment by artur-beljajev** [comment] 2017-05-26 17:54
https://gist.github.com/ratM1n/5717863b39877015bea3870d241b103d
https://gist.github.com/ratM1n/e50f0b2aa08e00c481a7c0263a3cb206

**Comment by artur-beljajev** [comment] 2017-06-01 11:47
#507

**Comment by vohmar** [comment] 2017-06-01 13:46
* Unexpired filter returns zero rows in staging although plenty of active price records exist.
* expired a price list record but could still register a domain for that period with the price of expired domain (looks like expire action makes the record expired starting from a new day)

**Comment by artur-beljajev** [comment] 2017-06-02 15:41
№ 1: Fixed (NULL in valid_to wasn't considered as effective). Introduced "pending" in status filter.
№ 2: #538

**Comment by vohmar** [comment] 2017-06-06 08:25
actions that user pricelist fail - ie domain:renew results with "not elligible for renewal" / "internal error" messages
few example on staging:
* /admin/epp_logs/45888
* /admin/epp_logs/45920

Seems to be a problem with atribute names:
FROM-EPP-RESCUE: unknown attribute 'log_pricelist_id' for AccountActivity.

**Comment by artur-beljajev** [comment] 2017-06-08 21:35
This is due to staging branch problems (see Skype chat for details)

**Comment by artur-beljajev** [comment] 2017-06-08 21:41
I merged #475 so now it should be ok

**Comment by vohmar** [comment] 2017-06-09 14:57
the fileters of the prices are no good
* effective filter does not include prices with startdate or enddate as today (these are in expired list instead)
* interface does not remember the filteres selected after returning from price edit view forcing user to reapply any filter they were using before.

**Comment by artur-beljajev** [comment] 2017-06-12 00:25
1. Not sure I understood the problem. Perhaps it's because #538? I checked "expired" list for anomalies, and didn't notice any. Also checked spec: https://github.com/internetee/registry/blob/f3e790b4817279df9c967016746adaebc9c081f7/spec/models/billing/price_spec.rb#L65-L65
and it also passed. It would be good if you check it.
2. If you go back using browser "back" button right after you clicked something on index page, then all filter params are preserved. If you edited, and clicked "save", sure it doesn't save filter params, since it requires save it somewhere in user session and there wasn't such requirement. Create additional ticket if you really need this, but keep in mind it introduces complexity, so this feature should be justified.

**Comment by vohmar** [comment] 2017-06-12 07:14
1. The problem is that admin cannot trust the data displayed by the admin interface - it shows effective price list items in expired list making the filters unreliable.
2. new ticket created (#542)

**Comment by vohmar** [comment] 2017-06-12 12:36
1. will be solved in #538 / #313

**Comment by vohmar** [comment] 2017-06-12 12:37
merge conflicts with master

**Comment by artur-beljajev** [comment] 2017-06-12 23:55
Staging is updated.

**Comment by vohmar** [comment] 2017-06-13 11:36
merged to master

**Comment by vohmar** [comment] 2017-06-16 13:30
in production

**Closed by vohmar** 2017-06-16 13:30 UTC
