### ISSUE TITLE
No email is sent on expiry of pendingUpdate

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#897] opened 2018-06-26 11:15 UTC
There is a confirmation process in place for registrant change where the current registrant is sent information about requested change and asked to confirm or deny it. There is a similar process for deleting domain using epp delete request. The request is valid for 48 hours for both cases, but in case of pendingUpdate the current nor applying registrant is informed if the request has been automatically canceled due to expiry.

expected behavior is that both current and applying registrants are notified about expired pending update request

closes https://github.com/internetee/registry/issues/292

**Comment by artur-beljajev** [comment] 2019-04-12 14:14
Seems like a duplicate of #292.

**Comment by vohmar** [comment] 2020-10-29 10:43
failing que job is created on expiry of penidngUpdate

https://st-adm.infra.tld.ee/admin/que/jobs/656137


Job | RegistrantChangeExpiredEmailJob
ArgumentError: SMTP To address may not be blank: []

**Comment by vohmar** [comment] 2021-03-03 14:20
the email about expired update request was sent only to existing registrant - nothing was sent to the registrant candidate.

**Closed** 2021-03-03 15:04 UTC
Labels: bug
