### ISSUE TITLE
EPP: update on a domain with deletecandidate status returns "not elligible for renewal"

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#405] opened 2017-03-02 13:26 UTC
epp domain:update request to a domain with deleteCandidate status results with incorrect error message

Object is not eligible for renewal [code: 2105]

**Comment by artur-beljajev** [comment] 2017-03-02 21:07
What is the correct message?

**Comment by vohmar** [comment] 2017-03-03 10:25
No code 2105 is the error message for invalid renewal request.
For invalid update or delete it is 
2304    "Object status prohibits operation"

while on the topic the transfer request for domain with deleteCandidate status should return
2106    "Object is not eligible for transfer"

An alternative to keep things as simple as possible would be to always return 2304 on every transform request (update, renew, transfer, delete) made for domains with deleteCandidate status

**Comment by artur-beljajev** [comment] 2019-09-13 18:50
Duplicate of https://github.com/internetee/registry/issues/718.

**Closed by artur-beljajev** 2019-09-13 18:50 UTC
Labels: bug
